# .github/workflows/release.yml
name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip ci]') == false && !contains(github.event.head_commit.message, 'chore(release)')"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Determine Next Version
        id: cliff
        run: |
          # Get the proposed version. If no new version, this will be empty.
          BUMPED_VERSION=$(bunx git-cliff --bumped-version)

          if [ -n "$BUMPED_VERSION" ]; then
            echo "New version determined: $BUMPED_VERSION"
            echo "HAS_NEW_VERSION=true" >> $GITHUB_OUTPUT
            echo "TAG=$BUMPED_VERSION" >> $GITHUB_OUTPUT
            echo "VERSION=${BUMPED_VERSION#v}" >> $GITHUB_OUTPUT
          else
            echo "No new version determined. Nothing to do."
            echo "HAS_NEW_VERSION=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate Changelog and Bump Version
        if: steps.cliff.outputs.HAS_NEW_VERSION == 'true'
        run: |
          bunx git-cliff --bump --output CHANGELOG.md --tag ${{ steps.cliff.outputs.TAG }}
          bun pm version ${{ steps.cliff.outputs.VERSION }} --no-git-tag-version

      - name: Commit and Push Changes
        if: steps.cliff.outputs.HAS_NEW_VERSION == 'true'
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No file changes to commit."
          else
            git commit -m "chore(release): ${{ steps.cliff.outputs.TAG }}"
            git tag "${{ steps.cliff.outputs.TAG }}"
            git push && git push --tags
          fi

      - name: Publish to Marketplace
        if: steps.cliff.outputs.HAS_NEW_VERSION == 'true'
        run: bun run release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Create GitHub Release
        if: steps.cliff.outputs.HAS_NEW_VERSION == 'true'
        run: |
          RELEASE_NOTES=$(bunx git-cliff --latest --strip all)
          gh release create "${{ steps.cliff.outputs.TAG }}" --notes "${RELEASE_NOTES}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
