name: Release and Publish

on:
  push:
    tags:
      - 'v*' # Runs only when a tag like v0.2.1 is pushed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Publish to VS Code Marketplace
        run: bun run release
        env:
          VS_MARKETPLACE_TOKEN: ${{ secrets.VSCE_TOKEN }}
