# .github/workflows/release.yml
name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip ci]') == false && (github.ref == 'refs/heads/main' && contains(toJson(github.event.commits), '.changeset/'))"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump Version and Update Changelog
        id: version
        run: |
          bun changeset version
          echo "VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_OUTPUT

      - name: Commit Version Changes
        run: |
          git add .
          git commit -m "chore(release): v${{ steps.version.outputs.VERSION }}"

      - name: Push Changes and Tags
        run: git push --follow-tags

      - name: Publish to Marketplace
        run: bun run release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Create GitHub Release
        run: |
          bunx changelog-github --token ${{ secrets.GITHUB_TOKEN }} --tag v${{ steps.version.outputs.VERSION }}
