name: Create Version PR

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          # This is needed to allow changesets to fetch previous tags
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Create Version PR or Update Existing
        id: changesets
        uses: changesets/action@v1
        with:
          # This will run `bun changeset version` and create a PR
          version: bun run version
          title: Upcoming Release
          commit: 'chore: update version and changelog'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
